version: '3'
services:
  elasticsearch:
    image: elasticsearch:5.6-alpine
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
